In [4]:
# Task 1:
# 1. Write a function to compute 5/0 and use try/except to catch the exceptions.

# function body
def num_opr():
    a = 5
    try:
        b = 5/0
    except:
        print('Division by zero is not permissible')
    else: 
        print('strange.Division by zero is indeed possible')
    finally:
        print('Exiting from the function')
        
# invoke the function
num_opr()


Division by zero is not permissible
Exiting from the function


In [1]:
# 2. Implement a Python program to generate all sentences where subject is in ["Americans",
#"Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

# Declare the Subject,Verb and Object lists.
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

# Iterate over the lists in nested for loops and print the list elements. 
for i in subjects:
    for j in verbs:
        for k in objects:
            print(i + ' '+ j + ' ' + k +'.')


Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


In [5]:
#Task 2
#Write a function so that the columns of the output matrix are powers of the input vector

import numpy as np

# Define the function
def Vandermonde(x,N):
    result = np.column_stack([x**(N-1-i) for i in range (N)])
    return result

# invoke the function
x = np.array([1, 2, 3, 5])
N=3
y = Vandermonde(x,N)
print(y)


[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [25  5  1]]
